# fly.toml app configuration file generated for new-api-z on 2025-04-23T17:59:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'new-api-z'
primary_region = 'hkg'

[build]

[http_service]
  internal_port        = 3000
  force_https          = true
  auto_start_machines  = true
  auto_stop_machines   = false
  min_machines_running = 1
  processes            = ["app"]

  [http_service.concurrency]
    type       = "requests"
    soft_limit = 9999
    hard_limit = 9999
