name: Upstream Sync

permissions:
  contents: write  # 允许写入分支

on:
  schedule:
    - cron: "0 1 * * *"  # 每天 UTC 时间 1 点同步（北京时间上午 9 点）
  workflow_dispatch:  # 允许手动触发

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: QuantumNous/new-api
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      - name: Sync check
        if: failure()
        run: |
          echo "[错误] 可能由于上游仓库更改了 workflow 文件，GitHub 自动暂停了同步。请手动同步一次 Fork。"
          exit 1
